/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class convertidor extends javax.swing.JFrame {

    /**
     * Creates new form convertidor
     */
    public convertidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Lres = new javax.swing.JLabel();
        TxtIngresar = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Convertidor de Moneda");

        jLabel2.setText("Ingrese Moneda");

        jLabel3.setText("Convercion");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lps", "Dollar", "Euro", "Yen", "Libra" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Convertir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Lres.setText(" ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lps", "Dollar", "Euro", "Yen", "Libra" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setText("De:");

        jLabel5.setText("A:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtIngresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(Lres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Lres))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double ing,res;
        ing=Double.parseDouble(this.TxtIngresar.getText());
        
        if(jComboBox1.getSelectedItem().toString().equals(jComboBox2.getSelectedItem().toString())){
            this.Lres.setText("elejir monedas diferentes");
        }else if(jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() == 1){
            this.Lres.setText(Integer.parseInt(TxtIngresar.getText())*0.04+"");
        }else if(jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() == 2){
            this.Lres.setText(""+(Integer.parseInt(TxtIngresar.getText())*0.0361));
        }else if(jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() == 3){
            this.Lres.setText(""+(Integer.parseInt(TxtIngresar.getText())*4.48));
        }else if(jComboBox1.getSelectedIndex() == 0 && jComboBox2.getSelectedIndex() == 4){
            this.Lres.setText(""+(Integer.parseInt(TxtIngresar.getText())*0.0309));
        }
        
        if(jComboBox1.getSelectedItem().toString().equals(jComboBox2.getSelectedItem().toString())){
            this.Lres.setText("elejir monedas diferentes");
        }else if(jComboBox1.getSelectedIndex() == 1 && jComboBox2.getSelectedIndex() == 0){
            this.Lres.setText(Integer.parseInt(TxtIngresar.getText())*24.2+"");
        }else if(jComboBox1.getSelectedIndex() == 1 && jComboBox2.getSelectedIndex() == 2){
            this.Lres.setText(""+(Integer.parseInt(TxtIngresar.getText())*0.88));
        }else if(jComboBox1.getSelectedIndex() == 1 && jComboBox2.getSelectedIndex() == 3){
            this.Lres.setText(""+(Integer.parseInt(TxtIngresar.getText())*109.93));
        }else if(jComboBox1.getSelectedIndex() == 1 && jComboBox2.getSelectedIndex() == 4){
            this.Lres.setText(""+(Integer.parseInt(TxtIngresar.getText())*0.76));
        }
        
        if(jComboBox1.getSelectedItem().toString().equals(jComboBox2.getSelectedItem().toString())){
            this.Lres.setText("elejir monedas diferentes");
        }else if(jComboBox1.getSelectedIndex() == 2 && jComboBox2.getSelectedIndex() == 0){
            this.Lres.setText(Integer.parseInt(TxtIngresar.getText())*27.72+"");
        }else if(jComboBox1.getSelectedIndex() == 2 && jComboBox2.getSelectedIndex() == 1){
            this.Lres.setText(""+(Integer.parseInt(TxtIngresar.getText())*1.13));
        }else if(jComboBox1.getSelectedIndex() == 2 && jComboBox2.getSelectedIndex() == 3){
            this.Lres.setText(""+(Integer.parseInt(TxtIngresar.getText())*124.29));
        }else if(jComboBox1.getSelectedIndex() == 2 && jComboBox2.getSelectedIndex() == 4){
            this.Lres.setText(""+(Integer.parseInt(TxtIngresar.getText())*0.86));
        }
        
        if(jComboBox1.getSelectedItem().toString().equals(jComboBox2.getSelectedItem().toString())){
            this.Lres.setText("elejir monedas diferentes");
        }else if(jComboBox1.getSelectedIndex() == 3 && jComboBox2.getSelectedIndex() == 0){
            this.Lres.setText(Integer.parseInt(TxtIngresar.getText())*0.22+"");
        }else if(jComboBox1.getSelectedIndex() == 3 && jComboBox2.getSelectedIndex() == 1){
            this.Lres.setText(""+(Integer.parseInt(TxtIngresar.getText())*0.0091));
        }else if(jComboBox1.getSelectedIndex() == 3 && jComboBox2.getSelectedIndex() == 2){
            this.Lres.setText(""+(Integer.parseInt(TxtIngresar.getText())*0.0080));
        }else if(jComboBox1.getSelectedIndex() == 3 && jComboBox2.getSelectedIndex() == 4){
            this.Lres.setText(""+(Integer.parseInt(TxtIngresar.getText())* 0.0069));
        }
        
        if(jComboBox1.getSelectedItem().toString().equals(jComboBox2.getSelectedItem().toString())){
            this.Lres.setText("elejir monedas diferentes");
        }else if(jComboBox1.getSelectedIndex() == 4 && jComboBox2.getSelectedIndex() == 0){
            this.Lres.setText(Integer.parseInt(TxtIngresar.getText())*32.40+"");
        }else if(jComboBox1.getSelectedIndex() == 4 && jComboBox2.getSelectedIndex() == 1){
            this.Lres.setText(""+(Integer.parseInt(TxtIngresar.getText())*1.32));
        }else if(jComboBox1.getSelectedIndex() == 4 && jComboBox2.getSelectedIndex() == 2){
            this.Lres.setText(""+(Integer.parseInt(TxtIngresar.getText())*1.17));
        }else if(jComboBox1.getSelectedIndex() == 4 && jComboBox2.getSelectedIndex() == 3){
            this.Lres.setText(""+(Integer.parseInt(TxtIngresar.getText())* 145.26));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.TxtIngresar.setText("");
        this.Lres.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new convertidor().setVisible(true);
            }
        });
    }   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lres;
    private javax.swing.JTextField TxtIngresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
